version: "3.9"

services:
  imc-postgres:
    image: postgres
    container_name: imc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: imc_user
      POSTGRES_PASSWORD: imc_pass
      POSTGRES_DB: imc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      # Mount init scripts folder â€“ everything in here runs on first init
      - ./initdb:/docker-entrypoint-initdb.d

  imc-pgadmin:
    image: dpage/pgadmin4
    container_name: imc-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - imc-postgres

volumes:
  postgres_data:
